# Generated by Django 3.0.8 on 2020-07-18 15:50

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200717_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_items', wagtail.core.fields.StreamField([('social_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock()), ('social_type', wagtail.core.blocks.ChoiceBlock(choices=[('fb', 'facebook'), ('tt', 'twitter')]))]))])),
            ],
        ),
        migrations.AlterField(
            model_name='navbar',
            name='menu_items',
            field=wagtail.core.fields.StreamField([('external_link', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(required=False)), ('fa_icon_class', wagtail.core.blocks.CharBlock(required=False)), ('link', wagtail.core.blocks.URLBlock()), ('children', wagtail.core.blocks.StreamBlock([('external_link', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(required=False)), ('fa_icon_class', wagtail.core.blocks.CharBlock(required=False)), ('link', wagtail.core.blocks.URLBlock())])), ('page_link', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(required=False)), ('fa_icon_class', wagtail.core.blocks.CharBlock(required=False)), ('page', wagtail.core.blocks.PageChooserBlock())]))], required=False))])), ('page_link', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(required=False)), ('fa_icon_class', wagtail.core.blocks.CharBlock(required=False)), ('page', wagtail.core.blocks.PageChooserBlock()), ('children', wagtail.core.blocks.StreamBlock([('external_link', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(required=False)), ('fa_icon_class', wagtail.core.blocks.CharBlock(required=False)), ('link', wagtail.core.blocks.URLBlock())])), ('page_link', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(required=False)), ('fa_icon_class', wagtail.core.blocks.CharBlock(required=False)), ('page', wagtail.core.blocks.PageChooserBlock())]))], required=False))]))]),
        ),
    ]
