# Generated by Django 3.0.8 on 2020-07-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200718_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='name',
            field=models.CharField(default='footer', max_length=255),
            preserve_default=False,
        ),
    ]
