# Generated by Django 3.0.8 on 2020-07-18 15:58

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_footer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitepage',
            name='footer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='website.Footer'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='social_items',
            field=wagtail.core.fields.StreamField([('social_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock()), ('social_type', wagtail.core.blocks.ChoiceBlock(choices=[('fb', 'facebook'), ('tt', 'twitter'), ('li', 'linked-in'), ('gh', 'github')]))]))]),
        ),
    ]
