# Generated by Django 3.0.8 on 2020-07-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_header_headeredpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='fill_view_height',
            field=models.BooleanField(default=False),
        ),
    ]
