# Generated by Django 3.0.8 on 2020-07-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_resumepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='lead_paragraph',
            field=models.CharField(default='here is the resume:', max_length=255),
        ),
    ]
