# Generated by Django 3.0.8 on 2020-07-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_resumepage_lead_paragraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumepage',
            name='lead_paragraph',
        ),
        migrations.AddField(
            model_name='resumepage',
            name='header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='website.Header'),
        ),
    ]
