# Generated by Django 3.0.8 on 2020-07-21 18:11

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_freeformpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeformpage',
            name='freeform_items',
            field=wagtail.core.fields.StreamField([('PDF', wagtail.core.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock())]))], blank=True, null=True),
        ),
    ]
