# Generated by Django 3.0.8 on 2020-07-21 18:33

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('website', '0013_freeformpage_freeform_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyhomepage',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='storyhomepage',
            name='header',
        ),
        migrations.RemoveField(
            model_name='storyhomepage',
            name='navbar',
        ),
        migrations.RemoveField(
            model_name='storyhomepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='storyhomepage',
            name='search_image',
        ),
        migrations.AlterField(
            model_name='freeformpage',
            name='freeform_items',
            field=wagtail.core.fields.StreamField([('pdf', wagtail.core.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock())])), ('timeline', wagtail.core.blocks.StructBlock([('timeline_items', wagtail.core.blocks.StreamBlock([('event', wagtail.core.blocks.StructBlock([]))]))]))], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ResumePage',
        ),
        migrations.DeleteModel(
            name='StoryHomePage',
        ),
    ]
