# Generated by Django 3.0.8 on 2020-07-21 20:42

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20200721_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeformpage',
            name='freeform_items',
            field=wagtail.core.fields.StreamField([('pdf', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Document', max_length=255)), ('description', wagtail.core.blocks.CharBlock(default='Example description', max_length=255)), ('document', wagtail.documents.blocks.DocumentChooserBlock())])), ('timeline', wagtail.core.blocks.StructBlock([('timeline_items', wagtail.core.blocks.StreamBlock([('event', wagtail.core.blocks.StructBlock([('date', wagtail.core.blocks.DateBlock(required=False)), ('header', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('lead_paragraph', wagtail.core.blocks.RichTextBlock(required=False))]))]))]))], blank=True, null=True),
        ),
    ]
