# Generated by Django 3.0.8 on 2020-07-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_articlelistingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlelistingpage',
            name='lead_paragraph',
            field=models.CharField(default='See latest articles.', max_length=255),
        ),
    ]
