# Generated by Django 3.0.8 on 2020-07-23 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20200723_0341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleTag',
        ),
    ]
