# Generated by Django 3.0.8 on 2020-07-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20200723_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='automatic_items_mode',
            field=models.BooleanField(default=True, help_text='override menu_items below and find links automatically using the include in navigation page option'),
        ),
    ]
