# Generated by Django 3.0.8 on 2020-07-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20200727_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='automatic_items_mode',
        ),
        migrations.AddField(
            model_name='navbar',
            name='generate_items_on_next_save',
            field=models.BooleanField(default=False, help_text="override menu_items below and find links automatically using the include in navigation page option when you next click 'save'"),
        ),
    ]
