# Generated by Django 3.0.8 on 2020-07-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_auto_20200729_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlelistingpage',
            name='lead_paragraph',
        ),
    ]
