# Generated by Django 3.0.8 on 2020-07-30 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_remove_articlelistingpage_lead_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlelistingpage',
            name='header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='website.Header'),
        ),
    ]
