# Generated by Django 3.0.8 on 2020-08-11 21:25

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('website', '0044_auto_20200811_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectarticlepage',
            name='project_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='website.ProjectArticlePageTag', to='taggit.Tag', verbose_name='Project tags'),
        ),
    ]
