# Generated by Django 3.1 on 2020-08-23 17:09

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_projectarticlepage_is_coursework'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectarticlepage',
            name='awards',
            field=wagtail.core.fields.StreamField([('award', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=255)), ('description', wagtail.core.blocks.CharBlock(max_length=1024)), ('award_value', wagtail.core.blocks.ChoiceBlock(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')]))], blank=True, null=True))], blank=True, null=True),
        ),
    ]
